### ISSUE TITLE
Not work in MySQL 5.7 and 8

### ISSUE THREAD

**Issue by Pandaver** [viascom/nanoid-mysql-mariadb#1]
Windows10 Docker Desktop

![截图_20230812144239](https://github.com/viascom/nanoid-mysql-mariadb/assets/62326552/4ea8c206-4cbb-4572-8d80-60d72f6ccb64)

![截图_20230812144259](https://github.com/viascom/nanoid-mysql-mariadb/assets/62326552/d1a06e49-e4ea-4cfb-a98b-8f4abe2f203d)

**Comment by nik-sta** [comment]
Hey @Pandaver, thanks for the issue! I'll check it out soon and get back to you. Cheers, Nikola

**Comment by nik-sta** [comment]
Hi @Pandaver. Is it a big deal if we set a condition that it only works with MySQL 5.7.4 or newer?

**Comment by nik-sta** [comment]
Feel free to reopen this issue if you have a problem or want to change anything regarding the changes made here.
