### ISSUE TITLE
Requirements reg MariaDB 

### ISSUE THREAD

**Issue by epistemologieVS** [viascom/nanoid-mysql-mariadb#3]
In requirements section, you state that nanoid works with MariaDB 10.1.1 or newer, however you use the function RANDOM_BYTES that was added to MariaDB not earlier than 10.10.0 (see [MariaDB documentation](https://mariadb.com/kb/en/random_bytes/))

**Comment by nik-sta** [comment]
You're right.  I've adjusted the README to match the correct version. Thx for taking the time to report the issue.
